
export const ACTIONS_TYPES = {
    OPEN_DIALOG_LOGIN: 'OPEN_DIALOG_LOGIN',
    CLOSE_DIALOG_LOGIN: 'CLOSE_DIALOG_LOGIN',

    OPEN_DIALOG_REGISTRATION: 'OPEN_DIALOG_REGISTRATION',
    CLOSE_DIALOG_REGISTRATION: 'CLOSE_DIALOG_REGISTRATION',
    
    CHANGE_NICKNAME_REGISTRATION: 'CHANGE_NICKNAME_REGISTRATION',
    CHANGE_EMAIL_REGISTRATION: 'CHANGE_EMAIL_REGISTRATION',
    CHANGE_PASSWORD_REGISTRATION: 'CHANGE_PASSWOD_REGISTRATION',
    RESET_FORM_REGISTRATION: 'RESET_FORM_REGISTRATION',

    CHANGE_EMAIL_LOGIN: 'CHANGE_EMAIL_LOGIN',
    CHANGE_PASSWORD_LOGIN: 'CHANGE_PASSWORD_LOGIN',
    RESET_FORM_LOGIN: 'RESET_FORM_LOGIN',
    AUTH_USER: 'AUTH_USER',
    LOGOUT_USER: 'LOGOUT_USER',
}