
export const ACTIONS_TYPES = {
    OPEN_DIALOG_LOGIN: 'OPEN_DIALOG_LOGIN',
    CLOSE_DIALOG_LOGIN: 'CLOSE_DIALOG_LOGIN',

    OPEN_DIALOG_REGISTRATION: 'OPEN_DIALOG_REGISTRATION',
    CLOSE_DIALOG_REGISTRATION: 'CLOSE_DIALOG_REGISTRATION',

    OPEN_DIALOG_CHANGE: 'OPEN_DIALOG_DIALOG',
    CLOSE_DIALOG_CHANGE: 'CLOSE_DIALOG_CHANGE',

    LOADING_START: 'LOADING_START',
    LOADING_SUCCESS: 'LOADING_SUCCESS',

    ERROR: 'ERROR',
    RESET_ERROR: 'RESET_ERROR',
    VISIBILITY_ERROR_ON: 'VISIBILITY_ERROR_ON',
    VISIBILITY_ERROR_OFF: 'VISIBILITY_ERROR_OFF',

    LOADING_ELEMENT_START: 'LOADING_ELEMENT_START',
    LOADING_ELEMENT_SUCCESS: 'LOADING_ELEMENT_SUCCESS',
    LOADING_ELEMENT_FAILURE: 'LOADING_ELEMENT_FAILURE',

    CHANGE_EMAIL_LOGIN: 'CHANGE_EMAIL_LOGIN',
    CHANGE_PASSWORD_LOGIN: 'CHANGE_PASSWORD_LOGIN',
    RESET_FORM_LOGIN: 'RESET_FORM_LOGIN',
    AUTH_USER: 'AUTH_USER',
    LOGOUT_USER: 'LOGOUT_USER',

    GET_MOVIES: 'GET_MOVIES',
    GET_MOVIE_LIST: 'GET_MOVIE_LIST',
    GET_MOVIE_DETAILS: 'GET_MOVIE_DETAILS',
    GET_REVIEW: 'GET_REVIEW',
    GET_USER_REVIEW: 'GET_USER_REVIEW',

}